### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by dmanconivmware** [ModernAppsNinja/introtanzustandard_ts7297#3]
Hi, the links to Introduction to "VMware Tanzu Portfolio", "ModernApps Ninja 101 course" do not work correctly. 

VMware Tanzu Portfolio goes to https://modernapps.ninja/courses/course-v1:modernapps+COU-TP6539+Perpetual/course/ and a 404 error,  but I think should go to https://learning.customerconnect.vmware.com/oltpublish/site/program.do?dispatch=showProgramSession&id=88e8048b-021f-11eb-9f48-0cc47adeb5f8 

ModernApps Ninja should go to https://modernapps.ninja/course/modernappsninja101/, but goes to https://modernapps.ninja/courses/course-v1:modernapps+COU-MN7417+Perpetual/course/ and a 404 error

Thanks

**Comment by afewell** [comment]
Hi @dmanconivmware thanks so much for catching this! We changed the link for these courses to be lms.modernapps.ninja ... everything else in the links provided is correct just need to prepend lms. 

That being said, the modernapps ninja 101 course hasnt been updated for our new platform yet so its probably  best to hold out on that one for a few weeks until I get it updated. Neither of the prerequisites is mandatory. 

It may take me a bit to make the update, I will leave this ticket open for tracking until I get the update made. Thanks so much!
