### ISSUE TITLE
i can not run my course after registration 

### ISSUE THREAD

**Issue by hasko0** [ModernAppsNinja/introtanzustandard_ts7297#445]
after I complete the registration i am try to access the course by using  this URL : https://modernapps.ninja/introtanzustandard_ts7297   but  I can't see the  contents

**Comment by afewell** [comment]
Hi @hasko0 I am sorry to hear about this issue! I am not sure how to resolve this, I am able to access the site without any problems, and I havent had any other reports like this. We host this on github pages, so it should have the same accessibility as any other site hosted by github pages. 

There are a couple workarounds that may help. 

(1) You could clone the repository and run it locally, its pretty easy to do. You would need to install hugo which is very easy, for windows I recommend using the chocolatey package manager, and on linux or mac using homebrew, its super easy. Its also pretty easy if you prefer not to use a package manager you can find full installation instructions on the Hugo website at [http://gohugo.io](http://gohugo.io). I recommend using the official instructions as info on random sites may be outdated. 

Once you have hugo installed, you just clone the course from its github homepage ([https://github.com/ModernAppsNinja/introtanzustandard_ts7297](https://github.com/ModernAppsNinja/introtanzustandard_ts7297)), navigate to the root of the cloned directory, and enter the command `hugo server` and it should run the website on your local computer exactly as it is on the public website. 

(2) Another option is, all of the same content is viewable directly on github, the source for the html files is in markdown and github has a built-in markdown reader that displays the content nicely. The trickiest part of viewing the content on github directly is that it is a little tricky to see which order the files should be read in, but all of the course content is in the content/en/docs directory, and in the top part of each markdown file there is a value for weight, and the files should be read in the order from lowest to highest weight. For that reason it is much easier to clone the repository and serve it locally with hugo if you cant access the public site. 

I hope one of those options works out for you!

**Comment by hasko0** [comment]
Hi ,Good News .Now it's working fine ,  we have restrictions in corporate Network 
Best regards

Hassan Aloshari 
 
  On Tue, Feb 1, 2022 at 12:13 PM, Arthur ***@***.***> wrote:   


Hi @hasko0 I am sorry to hear about this issue! I am not sure how to resolve this, I am able to access the site without any problems, and I havent had any other reports like this. We host this on github pages, so it should have the same accessibility as any other site hosted by github pages.

There are a couple workarounds that may help.

(1) You could clone the repository and run it locally, its pretty easy to do. You would need to install hugo which is very easy, for windows I recommend using the chocolatey package manager, and on linux or mac using homebrew, its super easy. Its also pretty easy if you prefer not to use a package manager you can find full installation instructions on the Hugo website at http://gohugo.io. I recommend using the official instructions as info on random sites may be outdated.

Once you have hugo installed, you just clone the course from its github homepage (https://github.com/ModernAppsNinja/introtanzustandard_ts7297), navigate to the root of the cloned directory, and enter the command hugo server and it should run the website on your local computer exactly as it is on the public website.

(2) Another option is, all of the same content is viewable directly on github, the source for the html files is in markdown and github has a built-in markdown reader that displays the content nicely. The trickiest part of viewing the content on github directly is that it is a little tricky to see which order the files should be read in, but all of the course content is in the content/en/docs directory, and in the top part of each markdown file there is a value for weight, and the files should be read in the order from lowest to highest weight. For that reason it is much easier to clone the repository and serve it locally with hugo if you cant access the public site.

I hope one of those options works out for you!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by afewell** [comment]
@hasko0 glad you got it working!
