### ISSUE TITLE
Additional Tanzu Mission Control Resources

### ISSUE THREAD

**Issue by pescerosso** [ModernAppsNinja/introtanzustandard_ts7297#458]
Add hyperlink to TMC course https://labs.hol.vmware.com/HOL/catalogs/lab/10506

**Comment by khbrady** [comment]
I try to avoid a hyperlink in case they do a re-name or reshuffling. But up to you

**Comment by pescerosso** [comment]
If the do, we can fix the link. But it is easier for people to click rather than search.

**Comment by khbrady** [comment]
Updated and added link
